<?php
/**
 * @file
 * Code for the CT Event feature.
 */

include_once('cmtls_event.features.inc');

/**
 * Implements hook_cmtls_app
 * 
 * @see cmtls.module
 */
function cmtls_event_cmtls_app() {
  return array(
    'cmtls_event' => array(
      'title' => t('Events'),
      'description' => t('Events with a ...'),
      'node types' => array(
        'cmtls_event' => t('Event'),
      ),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 * 
 * adds autocomplete for the location
 */
function cmtls_event_form_cmtls_event_node_form_alter(&$form, &$form_state, $form_id) {
  drupal_add_js(drupal_get_path('module', 'cmtls_location') . '/js/cmtls.location_ac.js');
}

