<?php
/**
 * Context API implementations
 */
include_once('cmtls_event.contexts.inc');

/**
 * Context API implementations
 */
include_once('cmtls_event.views.inc');

/**
 * Implementation of hook_ctools_plugin_api().
 */
function cmtls_event_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
}

/**
 * Implementation of hook_views_api().
 */
function cmtls_event_views_api() {
  list($module, $api) = func_get_args();
  if ($module == "views" && $api == "views_default") {
    return array("version" => "3.0");
  }
}

/**
 * Implementation of hook_node_info().
 */
function cmtls_event_node_info() {
  $items = array(
    'cmtls_event' => array(
      'name' => t('CT Event'),
      'base' => 'node_content',
      'description' => t('Community Tools event'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}

/**
 * Implements hook_cmtls_app
 * 
 * @see cmtls.module
 */
function cmtls_event_cmtls_app() {
  return array(
    'cmtls_event' => array(
      'title' => t('Events'),
      'description' => t('Events with a ...'),
      'node types' => array(
        'cmtls_event' => t('Event'),
      ),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 * 
 * adds autocomplete for the location
 */
function cmtls_event_form_cmtls_event_node_form_alter(&$form, &$form_state, $form_id) {
  drupal_add_js(drupal_get_path('module', 'cmtls') . '/js/cmtls.location_ac.js');
}

